// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzSUfo5R69MX00oiThOQB2g6NnifAYmU',
    appId: '1:259193193365:web:68d6bd7aac07526976ac9c',
    messagingSenderId: '259193193365',
    projectId: 'newsapp-bdff9',
    authDomain: 'newsapp-bdff9.firebaseapp.com',
    storageBucket: 'newsapp-bdff9.appspot.com',
    measurementId: 'G-9QBZ3TMN1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVxzeGDatzF7saUQGIcDN4GoAz1NgWJw',
    appId: '1:259193193365:android:909974e071cd59da76ac9c',
    messagingSenderId: '259193193365',
    projectId: 'newsapp-bdff9',
    storageBucket: 'newsapp-bdff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD4ix9HmL9RwWjPNFGcKTC1Oo0dpgpdR4',
    appId: '1:259193193365:ios:331a0d5dc92ee51576ac9c',
    messagingSenderId: '259193193365',
    projectId: 'newsapp-bdff9',
    storageBucket: 'newsapp-bdff9.appspot.com',
    iosClientId: '259193193365-ec39rto82ave8jeuqbabkr5qs00jnse7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD4ix9HmL9RwWjPNFGcKTC1Oo0dpgpdR4',
    appId: '1:259193193365:ios:b780046ed747fc1e76ac9c',
    messagingSenderId: '259193193365',
    projectId: 'newsapp-bdff9',
    storageBucket: 'newsapp-bdff9.appspot.com',
    iosClientId: '259193193365-l1pill4dg4g3n0gkv9vm8h8hp2jniamf.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapplication.RunnerTests',
  );
}
